### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by AFlex1920** [AndrewNguyen192257/github-crash-course#1]
I think it looks better if the main titile is a bit more orange.
the styling rule could be changed like this

```css
h1 {
  color: #ecbc68;
}
```
